### PR TITLE
Executable File, Named Exports, Project Updates

### PR DESCRIPTION
**Pull request by dezren39**
Expects to be merged after #8, made in response to suggestion to split out #6 into 'chunkType changes' (#8) and 'syntax/package changes' (this PR)

All existing tests still pass. Wouldn't recommend merging _before_ #8.

Changes include:
- Dependency Upgrades
- executable `bin/server.js` file
- ignore any `package-lock.json` files
- prefer `const > let > var`
- Made some subjective changes to pre-existing tests to better allow them to be read in a variety of terminals/fonts.
   - When working with emoji, I've had issues where they display differently everywhere.
   - Parsing the variable names has been easier overall, while sometimes more annoying on properly encoding editors.
- package changes (exports, run-scripts, bin files, keywords)
  - To allow easier compatibility with shell, etc:
    -  npm run-scripts: start, chunk, chunk-text
    -  bin/server.js
    -  package.json bin property
  - package.json module, exports, properties.
  - Added keywords to package.json
- Worked towards ESM-native code with CJS backwards compatibility.
  - Switched code/tests to imports.
  - package.json module, exports, properties.
  - CJS require still compatible.
  - Local build/dev may have new engine compatibility limitations.
  - I was unable to actually set "type":"module", so I clarified package.json property: "type":"commonJs"
    - The issue I had was jest and babel had different compatibility issues, their solutions seemed to conflict.
    - None of the other PRs related to the errors I found had any working solutions.
    - Jest devs didn't get community feedback in 2019 to prioritize ES support.
    - I considered other solutions, but already had made enough major changes for one PR.
       - On this note, I know algolia uses this for a lot of processing or something. I haven't performance tested anything and literally have just seen it "work on my machine". I made the changes for my own needs, but in order to get them mainlined can definitely rip out anything like imports instead of requires or something if it better aligns with something I'm missing. For instance, I updated a bunch of babel things and maybe you had a reason for locking it where it was outside of this module's requirements. 
- Incremented minor version, because although adding a parameter isn't a breaking change --
   - I do worry the overall changes may have some possibility of compatibility issue. Babel helps alleviate this concern though.
   - The effort to allow this capability has increased the complexity of this project.
      - I've tried to add enough testing to mitigate for the risks this presents.
   - Same version as #8, if separate release then may need to increment again.

### CODE REVIEW

**Comment by dezren39** [comment]
the changes between #8 and #9 are contained in commit: https://github.com/algolia/chunk-text/pull/9/commits/c5d81d1ead3c34fb398a84a8e9959560625e188a

**Comment by Haroenv** [comment]
looks like there's some conflicts now @dezren39, let's fix those so we can release both changes at once :)

**Comment by dezren39** [comment]
on it :)

**Comment by dezren39** [comment]
all tests pass and i fixed the merge, i think it's about ready but i'll try and run some manual tests tonight or this weekend :)

**Comment by dezren39** [comment]
updated my project deps and it's all working well, tests still passing, updated deps one last time

**Review by Haroenv — APPROVED** [review]

**Pull request merged**
